apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-city-weather-app
  namespace: gitops-kubernetes
  labels:
    app: my-city-weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-city-weather-app
  template:
    metadata:
      labels:
        app: my-city-weather-app
    spec:
      containers:
      - name: my-city-weather-app
        image: pietrolibro/gitops-k8s-deployments:main
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
