apiVersion: v1
kind: Service
metadata:
  name: my-city-weather-app-service
  namespace: gitops-kubernetes
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: my-city-weather-app
